version: '3.1'

services: 

  dupral:
    image: drupal:8-apache
    ports: 
      - 8888:80
    volumes: 
      # - drupal-modules:/var/www/html/modules
      - /var/www/html/modules
      # - drupal-profiles:/var/www/html/profiles
      - /var/www/html/profiles
      # - drupal-themes:/var/www/html/themes
      - /var/www/html/themes
      # - drupal-sites:/var/www/html/sites
      - /var/www/html/sites
    restart: always

  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: pass 
    restart: always

# volumes:
#   drupal-modules:
#   drupal-profiles:
#   drupal-sites:
#   drupal-themes: