# create your drupal and postgres config here, based off the last assignment

version: '3.1'

services: 

  dupral:
    image: custom-drupal
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8888:80
    volumes: 
      - drupal-modules:/var/www/html/modules
      # - /var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      # - /var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      # - /var/www/html/themes
      - drupal-sites:/var/www/html/sites
      # - /var/www/html/sites
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: pass 
    restart: always
    volumes: 
      - drupal-data:/var/lib/postgres/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: